# Generated by Django 4.2 on 2023-11-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Maths', 'Maths'), ('Statistics', 'Statistics'), ('Physics', 'Physics'), ('Electrical Engineering', 'Electrical Engineering'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Environmental Science', 'Environmental Science')], max_length=50, null=True),
        ),
    ]
